// AUTO-GENERATED by sim/lqr_design.py - do not edit by hand.
// Re-run `python3 sim/lqr_design.py` after changing design/params.py.
#pragma once
#include "bolt_controller.h"

namespace bolt {

inline RobotConfig default_config() {
  RobotConfig c{};
  c.l1 = 0.14f;
  c.l2 = 0.25f;
  c.l5 = 0.09f;
  c.wheel_radius = 0.075f;
  c.track = 0.364f;
  c.m_body = 4.204f;
  c.body_com_x = -0.00529225f;
  c.body_com_z = 0.0235219f;
  c.m_leg = 1.1159f;
  c.com_height_nom = 0.26459f;
  c.hip_torque_peak = 7.0f;
  c.hip_torque_cont = 3.0f;
  c.wheel_torque_peak = 4.0f;
  c.hip_speed_max = 20.0f;
  c.wheel_speed_max = 36.0f;
  c.L_min = 0.13f;
  c.L_nom = 0.22f;
  c.L_max = 0.35f;
  c.v_max = 2.0f;
  c.acc_max = 2.5f;
  c.yaw_rate_max = 3.0f;
  c.pitch_cmd_max = 0.45f;
  c.roll_cmd_max = 0.3f;
  c.K[0][0][0] = 8.61329f; c.K[0][0][1] = 78.9868f; c.K[0][0][2] = -72.5703f; c.K[0][0][3] = 58.7209f;
  c.K[0][1][0] = 1.00759f; c.K[0][1][1] = 9.66224f; c.K[0][1][2] = 13.3068f; c.K[0][1][3] = -7.83273f;
  c.K[0][2][0] = -9.57357f; c.K[0][2][1] = -12.6471f; c.K[0][2][2] = 40.9425f; c.K[0][2][3] = -45.2252f;
  c.K[0][3][0] = -9.06963f; c.K[0][3][1] = -2.31488f; c.K[0][3][2] = -4.75613f; c.K[0][3][3] = 4.22155f;
  c.K[0][4][0] = -22.6692f; c.K[0][4][1] = 139.056f; c.K[0][4][2] = -378.099f; c.K[0][4][3] = 377.388f;
  c.K[0][5][0] = -2.1247f; c.K[0][5][1] = 10.2506f; c.K[0][5][2] = -27.0785f; c.K[0][5][3] = 26.4785f;
  c.K[1][0][0] = 12.6266f; c.K[1][0][1] = -62.9114f; c.K[1][0][2] = 159.627f; c.K[1][0][3] = -153.341f;
  c.K[1][1][0] = 1.6852f; c.K[1][1][1] = -7.69399f; c.K[1][1][2] = 19.5109f; c.K[1][1][3] = -18.9284f;
  c.K[1][2][0] = -11.1297f; c.K[1][2][1] = 73.9732f; c.K[1][2][2] = -203.119f; c.K[1][2][3] = 203.444f;
  c.K[1][3][0] = -9.8257f; c.K[1][3][1] = 67.618f; c.K[1][3][2] = -191.169f; c.K[1][3][3] = 195.51f;
  c.K[1][4][0] = 41.743f; c.K[1][4][1] = 87.7557f; c.K[1][4][2] = -279.863f; c.K[1][4][3] = 306.763f;
  c.K[1][5][0] = 2.67519f; c.K[1][5][1] = 8.85756f; c.K[1][5][2] = -27.2252f; c.K[1][5][3] = 29.2476f;
  c.kp_leg = 900.0f;
  c.kd_leg = 45.0f;
  c.kp_roll = 250.0f;
  c.kd_roll = 18.0f;
  c.ki_roll = 120.0f;
  c.kp_yaw = 1.2f;
  c.kd_yaw = 0.01f;
  c.kp_sync = 25.0f;
  c.kd_sync = 1.5f;
  c.L_crouch = 0.142f;
  c.L_takeoff = 0.338f;
  c.L_retract = 0.15f;
  c.thrust_force = 420.0f;
  c.jump_clearance = 0.05f;
  c.fall_pitch = 0.85f;
  c.fall_roll = 0.75f;
  c.comm_timeout = 0.3f;
  c.ki_yaw = 6.0f;
  return c;
}

}  // namespace bolt
